[env]
TERM = "xterm-256color"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }

size = 10.2
builtin_box_drawing = true

[scrolling]
history = 10000
multiplier = 3

[terminal]
shell = { program = "/bin/bash", args = [ "--login"] }

[window]
decorations = "none"
startup_mode = "Maximized"

[colors]
draw_bold_text_with_bright_colors = true

[general]
live_config_reload = true
import = ["gruvbox_dark.toml"]

[mouse]
bindings = [
    { mouse = "Right", mods = "Shift", action = "Copy" },
    { mouse = "Right", mods = "Shift", action = "ClearSelection" },
]
