format = """
${env_var.STARSHIP_HOST}\
$username\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$c\
$cmake\
$lua\
$nodejs\
$python\
$buf\
$memory_usage\
$direnv\
$custom\
$sudo\
$cmd_duration\
$fill\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

palette = 'gruvbox'

[character]
format = "$symbol "
success_symbol = "[❯](bright_orange)"
error_symbol = "[❯](bright_red)"
disabled = false

[git_branch]
style = 'bright_orange'

[container]
disabled = true

[directory]
style = 'bold light0'

[env_var.STARSHIP_HOST]
format="[$env_value](bold bright_aqua) "

[fill]
style = "#333333"
symbol = '─'

[palettes.gruvbox]
dark0_hard = '#1d2021'
dark0 = '#282828'
dark0_soft = '#32302f'
dark1 = '#3c3836'
dark2 = '#504945'
dark3 = '#665c54'
dark4 = '#7c6f64'

light0_hard = '#fb4934'
light0 = '#fbf1c7'
light0_soft = '#f2e5bc'
light1 = '#ebdbb2'
light2 = '#d5c4a1'
light3 = '#bdae93'
light4 = '#a89984'

bright_red = '#fb4934'
bright_green = '#b8bb26'
bright_yellow = '#fabd2f'
bright_blue = '#83a598'
bright_purple = '#d3869b'
bright_aqua = '#8ec07c'
bright_orange = '#fe8019'

red = '#cc241d'
green = '#98971a'
yellow = '#d79921'
blue = '#458588'
purple = '#b16286'
aqua = '#689d6a'
orange = '#d65d0e'

faded_red = '#9d0006'
faded_green = '#79740e'
faded_yellow = '#b57614'
faded_blue = '#076678'
faded_purple = '#8f3f71'
faded_aqua = '#427b58'
faded_orange = '#af3a03'
